# Generated by Django 3.0.3 on 2020-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('quantity_instocks', models.IntegerField()),
                ('warranty_status', models.CharField(max_length=150)),
                ('distributer_info', models.TextField()),
                ('model_number', models.IntegerField()),
            ],
        ),
    ]
