# Generated by Django 3.0.3 on 2020-03-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_of_product',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
