# Generated by Django 3.0.3 on 2020-03-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_product_image_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_of_product',
            field=models.ImageField(upload_to='product_app/'),
        ),
    ]
