# Generated by Django 3.0.3 on 2020-03-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20200323_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_of_product',
            field=models.ImageField(blank=True, null=True, upload_to='product_app/'),
        ),
    ]
