# Generated by Django 3.0.3 on 2020-03-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20200323_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
