# Generated by Django 3.0.3 on 2020-03-26 03:50

from django.db import migrations, models
import product_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_auto_20200323_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_of_product',
            field=models.ImageField(blank=True, null=True, upload_to=product_app.models.upload_image_path),
        ),
    ]
