# Generated by Django 3.0.3 on 2020-04-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
