# Generated by Django 3.0.3 on 2020-04-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0002_address_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='delivery_profile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
