# Generated by Django 3.0.3 on 2020-04-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0002_address_address_name'),
        ('orders', '0005_auto_20200424_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_app.Address'),
        ),
    ]
