# Generated by Django 3.0.3 on 2020-03-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
